project_id = "uwatntzozavzfhnkiowd"

[functions.calculate-match-score]
verify_jwt = false

[functions.diagnose-enrichment]
verify_jwt = false

[functions.enrich-company-details]
verify_jwt = false

[functions.enrich-facebook]
verify_jwt = false

[functions.enrich-lead]
verify_jwt = false

[functions.find-company-coordinates]
verify_jwt = false

[functions.get-company-news]
verify_jwt = false

[functions.score-industry-relevance]
verify_jwt = false
