project_id = "uwatntzozavzfhnkiowd"

[functions.calculate-match-score]
verify_jwt = false

[functions.diagnose-enrichment]
verify_jwt = false

[functions.enrich-company-details]
verify_jwt = false

[functions.enrich-contact]
verify_jwt = false

[functions.enrich-facebook]
verify_jwt = false

[functions.enrich-lead]
verify_jwt = false

[functions.find-company-contacts]
verify_jwt = false

[functions.find-company-coordinates]
verify_jwt = false

[functions.get-company-news]
verify_jwt = false

[functions.score-industry-relevance]
verify_jwt = false

[functions.search-facebook-serper]
verify_jwt = false

[functions.search-linkedin-serper]
verify_jwt = false

[functions.search-instagram-serper]
verify_jwt = false

[functions.score-social-relevance]
verify_jwt = false

[functions.calculate-distance]
verify_jwt = false

[functions.score-domain-relevance]
verify_jwt = false

[functions.generate-vehicle-interest]
verify_jwt = false

[functions.generate-short-summary]
verify_jwt = false

[functions.generate-long-summary]
verify_jwt = false
